# Generated by Django 4.1.6 on 2023-02-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('antecipation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='antecipation.requestantecipation')),
                ('requester', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to='user_profile.operator')),
            ],
        ),
    ]
