# Generated by Django 4.1.6 on 2023-02-21 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('antecipation', '0002_antecipation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_after', models.CharField(max_length=20)),
                ('value_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operator', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.operator')),
                ('request', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='antecipation.requestantecipation')),
            ],
        ),
    ]
