# Generated by Django 4.1.6 on 2023-02-22 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('antecipation', '0005_requestantecipation_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtransactions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
