# Generated by Django 4.1.6 on 2023-02-22 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antecipation', '0007_alter_requestantecipation_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestantecipation',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
