# Generated by Django 4.1.6 on 2023-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antecipation', '0008_alter_requestantecipation_requester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecipation',
            old_name='fee',
            new_name='new_value',
        ),
        migrations.AddField(
            model_name='requestantecipation',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
