# Generated by Django 4.1.6 on 2023-02-22 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_operator_options'),
        ('antecipation', '0009_rename_fee_antecipation_new_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logtransactions',
            old_name='request',
            new_name='request_antecipation',
        ),
        migrations.AlterField(
            model_name='antecipation',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to='user_profile.operator'),
        ),
        migrations.AlterField(
            model_name='logtransactions',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.operator'),
        ),
    ]
