# Generated by Django 4.1.6 on 2023-02-22 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antecipation', '0010_rename_request_logtransactions_request_antecipation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logtransactions',
            name='operator',
        ),
        migrations.AddField(
            model_name='logtransactions',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logtransactions',
            name='transaction_type',
            field=models.CharField(choices=[('0', 'Request'), ('1', 'Approval'), ('2', 'Disapproval')], default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logtransactions',
            name='request_antecipation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='antecipation.requestantecipation'),
        ),
    ]
